carla_wpt:
  &carla_wpt # It's a base configuration for wpt tasks, don't use it directly
  reward:
    desired_speed: 4 # desired speed (m/s)
    scales:
      {
        waypoint: 2.0,
        speed: 0.5,
        collision: 30.0,
        out_of_lane: 3.0,
        time: 0.0,
        destination_reached: 20.0,
      }
  terminal:
    time_limit: 500 # maximum timesteps per episode
    out_lane_thres: 3 # threshold for out of lane

carla_navigation:
  env:
    name: CarlaNavigationEnv-v0
    observation.enabled: [camera, collision, birdeye_wpt]
    num_vehicles: 50
    <<: *carla_wpt

  dreamerv3:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    run.log_keys_video: [camera, birdeye_wpt]

  dreamerv2:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_kernels: [5, 5, 5, 6, 6]
    train.log_keys_video: [camera, birdeye_wpt]

carla_four_lane:
  env:
    name: CarlaFourLaneEnv-v0
    observation.enabled: [camera, collision, birdeye_wpt]
    num_vehicles: 50
    <<: *carla_wpt
    lane_start_points:
      - [5.8, 100, 0.1]
      - [9.0, 100, 0.1]
      - [12.2, 100, 0.1]
      - [15.6, 100, 0.1]
    lane_end_points:
      - [5.8, -58, 0.1]
      - [9.0, -58, 0.1]
      - [12.2, -58, 0.1]
      - [15.6, -58, 0.1]

  dreamerv3:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    run.log_keys_video: [camera, birdeye_wpt]
    run.log_keys_max: "collision"

  dreamerv2:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_kernels: [5, 5, 5, 6, 6]
    train.log_keys_video: [camera, birdeye_wpt]

carla_overtake:
  env:
    name: CarlaOvertakeEnv-v0
    observation.enabled: [collision, birdeye_wpt]
    nonego_spawn_points:
      - [5.8, 80.0, 0.1, 0.0, -90.0, 0.0]
      - [12.2, 80.0, 0.1, 0.0, -90.0, 0.0]
    lane_start_points:
      - [5.8, 100, 0.1]
    lane_end_points:
      - [5.8, 0.0, 0.1]
    swing_steer: 0.04 # The background vehicle steer for swing .
    swing_amplitude: 0.2 # The y-axis amplitude of background vehicle steer.
    swing_trigger_dist: 20 # The distance between ego and background vehicle that triggers swing.
    pid_coeffs: [0.03, 0.0, 0.03] # The PID controller parameter for background vehicle lane keeping.
    reward:
      desired_speed: 5 # desired speed (m/s)
      reward_overtake_dist: 8 # The distance that triggers overtake reward.
      early_lane_change_dist: 10 # The distance that penalizes early lane change.
      lane_width: 3.4
      scales:
        {
          waypoint: 2.0,
          speed: 0.5,
          stay_same_lane: 0.3,
          out_of_lane: 3.0,
          collision: 30.0,
          time: 0.0,
          exceeding: 200.0,
          overtake: 200.0,
          early_lane_change: 0.0,
          destination_reached: 20.0,
        }
    terminal:
      out_lane_thres: 5 # threshold for out of lane
      time_limit: 500 # maximum timesteps per episode
      left_lane_boundry: 3.7 # out of lane boundry
      right_lane_boundry: 17.7
      lane_width: 3.4
      terminal_dist: 100 # terminate tasks

  dreamerv3:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    run.log_keys_video: [birdeye_wpt]

  dreamerv2:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_kernels: [5, 5, 5, 6, 6]
    train.log_keys_video: [birdeye_wpt]

carla_right_turn_simple: &carla_right_turn_simple
  env:
    world:
      town: Town03
    name: CarlaRightTurnEnv-v0
    action:
      discrete_steer: [-0.9, -0.3, 0.0, 0.3, 0.9]
    observation.enabled: [camera, collision, birdeye_wpt]
    <<: *carla_wpt
    lane_start_point: [-33.8, -135.1, 0.1, 0.0]
    ego_path: [[-33.8, -135.1, 0.1], [-5.0, -110.3, 0.1]]
    use_road_waypoints: [True, False]
    flow_spawn_point: [-3.4, -151.2, 0.1, 90.0]

  dreamerv3:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    run.log_keys_video: [camera, birdeye_wpt]

  dreamerv2:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_kernels: [5, 5, 5, 6, 6]
    train.log_keys_video: [camera, birdeye_wpt]

carla_right_turn_medium:
  <<: *carla_right_turn_simple
  env.min_flow_dist: 8
  env.max_flow_dist: 16

carla_right_turn_hard:
  <<: *carla_right_turn_simple
  env.min_flow_dist: 6
  env.max_flow_dist: 8

carla_right_turn_random:
  env:
    world:
      town: Town03
    name: CarlaRightTurnRandomEnv-v0
    action:
      discrete_steer: [-0.9, -0.3, 0.0, 0.3, 0.9]
    observation.enabled: [camera, collision, birdeye_wpt]
    <<: *carla_wpt
    lane_start_point:
      [
        [-33.8, -135.1, 0.1, 0.0],
        [-3.2, -165.2, 0.1, 90],
        [9.3, -106.2, 0.1, -90]
      ]
    ego_path:
      [
        [[-33.8, -135.1, 0.1], [-5.0, -110.3, 0.1]],
        [[-3.2, -165.2, 0.1, 90], [-20.7, -142.2, 0.1, 180]],
        [[9.3, -106.2, 0.1, -90], [31.3, -130.7, 0.1, 0]]
      ]
    use_road_waypoints: [True, False]

  dreamerv3:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    run.log_keys_video: [camera, birdeye_wpt]

  dreamerv2:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_kernels: [5, 5, 5, 6, 6]
    train.log_keys_video: [camera, birdeye_wpt]

carla_left_turn_simple: &carla_left_turn_simple
  env:
    world:
      town: Town03
    name: CarlaLeftTurnEnv-v0
    observation.enabled: [camera, collision, birdeye_wpt]
    <<: *carla_wpt
    lane_start_point: [6.0, -101.0, 0.1, -90.0]
    ego_path: [[6.0, -101.0, 0.1], [-26.5, -139.0, 0.1]]
    use_road_waypoints: [True, False]
    flow_spawn_point: [-22.4, -135.4, 0.1, 0.0]

  dreamerv3:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    run.log_keys_video: [camera, birdeye_wpt]

  dreamerv2:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_kernels: [5, 5, 5, 6, 6]
    train.log_keys_video: [camera, birdeye_wpt]

carla_left_turn_medium:
  <<: *carla_left_turn_simple
  env.min_flow_dist: 8
  env.max_flow_dist: 16

carla_left_turn_hard:
  <<: *carla_left_turn_simple
  env.min_flow_dist: 6
  env.max_flow_dist: 8

carla_roundabout:
  env:
    world:
      town: Town03
      background_speed: 16
    name: CarlaRoundaboutEnv-v0
    observation.enabled: [camera, collision, birdeye_wpt]
    <<: *carla_wpt
    lane_start_point: [-52.6, 1.0, 0.1, 0.0]
    ego_path:
      [
        [-52.6, 1.0, 0.1],
        [-23.0, 7.5, 0.1],
        [-17.0, 11.7, 0.1],
        [13.3, -13.2, 0.1],
        [7.6, -21.8, 0.1],
        [4.2, -43.2, 0.1],
      ]
    use_road_waypoints: [True, False, True, False, True, False]
    flow_spawn_point: [-14.1, -13.5, 0.1, 125.0]
    min_flow_dist: 10
    max_flow_dist: 16
    terminal.out_lane_thres: 6

  dreamerv3:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    run.log_keys_video: [camera, birdeye_wpt]

  dreamerv2:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_kernels: [5, 5, 5, 6, 6]
    train.log_keys_video: [camera, birdeye_wpt]

carla_lane_merge:
  env:
    world:
      town: Town04
      background_speed: 25
    name: CarlaLaneMergeEnv-v0
    observation.enabled: [camera, collision, birdeye_wpt]
    <<: *carla_wpt
    reward.desired_speed: 6 # desired speed (m/s)
    lane_start_point: [49.4, 141.4, 0.5, -155.0]
    ego_path: [[49.4, 141.4, 0.5], [15.4, 56.0, 0.1]]
    use_road_waypoints: [True, False]
    flow_spawn_point: [16.2, 137.5, 0.1, -90.0]
    min_flow_dist: 8
    max_flow_dist: 14

  dreamerv3:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    run.log_keys_video: [camera, birdeye_wpt]

  dreamerv2:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_kernels: [5, 5, 5, 6, 6]
    train.log_keys_video: [camera, birdeye_wpt]

carla_traffic_lights:
  env:
    world:
      town: Town03
    name: CarlaTrafficLightsEnv-v0
    action:
      discrete_steer: [-0.9, -0.3, 0.0, 0.3, 0.9]
    observation.enabled: [camera, collision, birdeye_with_traffic_lights]
    observation.birdeye_with_traffic_lights.obs_range: 64
    reward:
      desired_speed: 4
      scales:
        waypoint: 2.0
        speed: 0.5
        collision: 30.0
        out_of_lane: 3.0
        time: 0.0
        destination_reached: 20.0
        traffic_light_violate: 100.0
    terminal:
      time_limit: 500 # maximum timesteps per episode
      out_lane_thres: 3 # threshold for out of lane

    lane_start_point:
      [
        [-0.3, -163.4, 0.1, 90.0],
        [-0.3, -163.4, 0.1, 90.0],
        [-3.5, -163.8, 0.1, 90.0],
        [-3.5, -163.8, 0.1, 90.0],
      ]
    ego_path:
      [
        [[-0.3, -163.4, 0.1], [32.5, -133.8, 0.1]],
        [[-0.3, -163.4, 0.1], [-1.5, -111.0, 0.1]],
        [[-3.5, -163.8, 0.1], [-4.7, -110.6, 0.1]],
        [[-3.5, -163.8, 0.1], [-27.0, -138.8, 0.1]],
      ]
    use_road_waypoints: [True, False]
    traffic_locations: [-3.4, -125.1, 0.1] # Location of traffic sign
    red_duration: [60, 80]
    green_duration: [40, 50]

    display:
      render_keys: [camera, birdeye_with_traffic_lights]

  dreamerv3:
    encoder.cnn_keys: "birdeye_with_traffic_lights"
    decoder.cnn_keys: "birdeye_with_traffic_lights"
    run.log_keys_video: [camera, birdeye_with_traffic_lights]

  dreamerv2:
    encoder.cnn_keys: "birdeye_with_traffic_lights"
    decoder.cnn_keys: "birdeye_with_traffic_lights"
    decoder.cnn_kernels: [5, 5, 5, 6, 6]
    train.log_keys_video: [camera, birdeye_with_traffic_lights]

carla_stop_sign:
  env:
    world:
      town: Town04
    name: CarlaStopSignEnv-v0
    action:
      discrete_steer: [-0.9, -0.3, 0.0, 0.3, 0.9]
    observation.enabled: [camera, collision, birdeye_with_traffic_lights]
    observation.birdeye_with_traffic_lights.obs_range: 64
    reward:
      desired_speed: 4
      scales:
        waypoint: 2.0
        speed: 0.5
        collision: 30.0
        out_of_lane: 3.0
        time: 0.0
        destination_reached: 20.0
        traffic_light_violate: 100.0
        stop_sign: 5.0
        speed_before_stop: 1.0
    terminal:
      time_limit: 500 # maximum timesteps per episode
      out_lane_thres: 3 # threshold for out of lane

    lane_start_point: [[179.5, -169.5, 5, 0.0]]
    ego_path: [[[179.5, -169.5, 0.1], [215.5, -169.1, 0.1]]]
    use_road_waypoints: [True, False]
    traffic_locations: [189.9, -169.6, 0.1] # Location of traffic sign
    stop_sign_proximity_threshold: 2
    stopping_time: 60 # How long should the vehicle stops

    display:
      render_keys: [camera, birdeye_with_traffic_lights]

  dreamerv3:
    encoder.cnn_keys: "birdeye_with_traffic_lights"
    decoder.cnn_keys: "birdeye_with_traffic_lights"
    run.log_keys_video: [camera, birdeye_with_traffic_lights]

  dreamerv2:
    encoder.cnn_keys: "birdeye_with_traffic_lights"
    decoder.cnn_keys: "birdeye_with_traffic_lights"
    decoder.cnn_kernels: [5, 5, 5, 6, 6]
    train.log_keys_video: [camera, birdeye_with_traffic_lights]
carla_follow:
  env:
    world:
      town: Town03
    name: CarlaFollowEnv-v0
    action:
      discrete_steer: [-0.9, -0.3, 0.0, 0.3, 0.9]
    observation.enabled: [camera, collision, birdeye_wpt]
    <<: *carla_wpt
    pid_coeffs: [0.03, 0.0, 0.0]
    reward:
      desired_speed: 4
      scales: {
        waypoint: 0.0,
        speed: 0.0,
        collision: 350.0,
        out_of_lane: 75.0,
        time: 0.0,
        destination_reached: 1.0,
        velocity: 0.15,
        waypoints: 4.0,
        distance: 2.0
      }


    terminal:
      time_limit: 500 # maximum timesteps per episode
      out_lane_thres: 5 # threshold for out of lane
      terminal_dist: 30

    direction: 2    # determining which direction we are testing
                    # 0: straight
                    # 1: right turn
                    # 2: left turn
                    # -1: random

    nonego_spawn_points:
      - [-53.6, -135.8, 0.1, 0.0, 0.0, 0.0] # straight
      - [-32.4, -135.3, 0.1, 0.0, 0.0, 0.0] # right turn
      - [-27.3, -135.2, 0.1, 0.0, 0.0, 0.0] # left turn
    lane_start_points:
      - [-63.6, -135.8, 0.1] # straight
      - [-42.4, -135.3, 0.1] # right turn
      - [-37.3, -135.2, 0.1] # left turn
    lane_end_points:
      - [-14.4, -134.5, 0.1] # straight
      - [-5.1, -91.1, 0.1] # right turn
      - [7.2, -178.2, 0.1] # left turn

  dreamerv3:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    run.log_keys_video: [birdeye_wpt]

  dreamerv2:
    encoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_keys: "birdeye_wpt"
    decoder.cnn_kernels: [5, 5, 5, 6, 6]
    train.log_keys_video: [birdeye_wpt]